const defaultStatusCodeResponses = {
	100: { message: 'Continue', success: true },
	101: { message: 'Mudando protocolos', success: true },
	200: { message: 'OK', success: true },
	201: { message: 'Criado', success: true },
	202: { message: 'Aceito', success: true },
	203: { message: 'Informações não autoritativas', success: true },
	204: { message: 'Sem conteúdo', success: true },
	205: { message: 'Conteúdo resetado', success: true },
	206: { message: 'Conteúdo parcial', success: true },
	300: { message: 'Múltipla escolha', success: true },
	301: { message: 'Movido permanentemente', success: true },
	302: { message: 'Encontrado', success: true },
	303: { message: 'Ver outras', success: true },
	304: { message: 'Não modificado', success: true },
	307: { message: 'Redirecionamento temporário', success: true },
	308: { message: 'Redirecionamento permanente', success: true },
	400: { message: 'Requisição inválida', success: false },
	401: { message: 'Não autorizado', success: false },
	402: { message: 'Pagamento necessário', success: false },
	403: { message: 'Proibido', success: false },
	404: { message: 'Não encontrado', success: false },
	405: { message: 'Método não permitido', success: false },
	406: { message: 'Não aceitável', success: false },
	407: { message: 'Autenticação de proxy necessária', success: false },
	408: { message: 'Tempo de requisição esgotado', success: false },
	409: { message: 'Conflito', success: false },
	410: { message: 'Indisponível', success: false },
	411: { message: 'Comprimento necessário', success: false },
	412: { message: 'Falha na pré-condição', success: false },
	413: { message: 'Payload muito grande', success: false },
	414: { message: 'URI muito longa', success: false },
	415: { message: 'Tipo de mídia não suportado', success: false },
	416: { message: 'Faixa não satisfatória', success: false },
	417: { message: 'Expectativa não cumprida', success: false },
	418: { message: 'Eu sou uma chaleira', success: false },
	421: { message: 'Requisição mal direcionada', success: false },
	422: { message: 'Entidade não processável', success: false },
	423: { message: 'Bloqueado', success: false },
	424: { message: 'Falha na dependência', success: false },
	426: { message: 'Upgrade necessário', success: false },
	428: { message: 'Pré-condição necessária', success: false },
	429: { message: 'Muitas requisições', success: false },
	431: { message: 'Campos de cabeçalho da requisição muito grandes', success: false},
	451: { message: 'Indisponível por motivos legais', success: false }
};

export default defaultStatusCodeResponses;
